### ISSUE TITLE
SCRIPT438: SCRIPT438: Object doesn't support property or method 'Symbol.iterator'

### ISSUE THREAD

**Issue by DanezBs** [lotrekagency/doria#4]
Hi,
I have this issue with IE and edge browser.
SCRIPT438: SCRIPT438: Object doesn't support property or method 'Symbol.iterator'

Can you check this?
Thx.
S.

**Comment by astagi** [comment]
Hi @DanezBs 

maybe is something related to this https://github.com/babel/babel/issues/4075 .. 

sorry but we haven’t tested it on ie11 and edge browsers yet, I think that fromArray on the html collection would fix the issue.. I’ll try it next week cause I’m out at the moment.. maybe @remeic can look at this issue.

Thanks for report

**Comment by Remeic** [comment]
Hi @DanezBs can you share more details? 
We need to know IE version, what function you enabled on doria.

Thanks!

**Comment by astagi** [comment]
Hey @DanezBs can you try this PR https://github.com/lotrekagency/doria/pull/5 ? we started adding support to ie11 with a different build, `doria-ie11.js`

**Comment by astagi** [comment]
The PR has been merged into master, we tested on ie11 and everything works using `doria-ie11.js` build. Feel free to open another issue if you have other problems. Thanks.
